CSS_PATH                    = './css/style.css'
JSON_PATH                   = './data/tree_structure.json'
TREE_JS_PATH                = './js/tree.js'
HIST_JS_PATH                = './js/histgram.js'
FIT_JS_PATH                 = './js/cov_fit.js'
TREE_JS_FOR_JUPYTER_PATH    = './js/tree_for_jupyter.js'
HIST_JS_FOR_JUPYTER_PATH    = './js/histgram_for_jupyter.js'
FIT_JS_FOR_JUPYTER_PATH     = './js/cov_fit_for_jupyter.js'